import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import api from './api/api';
import React from 'react';
import {
  LineChart,
  XAxis,
  CartesianGrid,
  Line,
  Tooltip,
  YAxis,
  Label
} from 'recharts'


function stocksearch() {
  
    // Create state variables
    let [responseData, setResponseData] = React.useState('');
    let [ticker, setTicker] = React.useState('');
    let [message, setMessage] = React.useState('');
 
    // fetches stock data based on parameters
    const fetchData = (e) => {
        e.preventDefault()
        setMessage('Loading...')
 
         api.stockTimeSeries(ticker)
         .then((response)=>{
             setResponseData(response.data)
             setMessage('')
             console.log(response)
         })
         .catch((error) => {
             setMessage('Error')
             console.log(error)
         })
     }
 
   return (
     <div className={styles.container}>
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
 
       <div
             style={{
                 background: 'white',
                 padding: '5%',
                 fontFamily: "Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,Bitstream Vera Sans Mono, Courier New, monospace "
             }}>
             <h1 className={styles.title}> Search </h1>
             <h2>Analyze Stock Data</h2>
             <form onSubmit={fetchData}>
                 <fieldset>
                     <legend>Search Stock Market</legend>
                     <label htmlFor="ticker">Enter stock ticker
                         <input
                             required
                             name="ticker"
                             id="ticker"
                             type='text'
                             placeholder='SPY'
                             value={ticker}
                             onChange={(e) => setTicker(e.target.value)}
                         />
                     </label>
                     <button type='submit'>Submit</button>
                 </fieldset>
             </form>
             <h1 className={styles.description}>{message}</h1>
 
             <h3 className={styles.title}> 
               <a > 
                 {responseData ? responseData.symbol : ''}
               </a> 
             </h3>
 
             <div className={styles.description}>Daily Time Series Data</div>
             <small>Last Refresh: {responseData ? responseData.refreshed : ''}</small>
             <LineChart
                 width={900}
                 height={500}
                 data={responseData.closePrices}
                 margin={{ top: 50, right: 20, left: 10, bottom: 5 }}
                 >
                 <YAxis tickCount={10} type="number" width={80}>
                     <Label value="Close Price" position="insideLeft" angle={270} />
                 </YAxis>
                 <Tooltip />
                 <XAxis padding={{left: 5, right: 5}} tickCount={10} angle={-20} height={90} dataKey="date" />
                 <CartesianGrid stroke="#b3b3b3" />
                 <Line type="monotone" dataKey="close" stroke="#2a9df4" yAxisId={0} />
             </LineChart>
         </div>
     </div>
 
   )
 }
 
export default stocksearch;

export async function getStaticProps(){


}