import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import api from '../pages/api/api'
import {
  LineChart,
  XAxis,
  CartesianGrid,
  Line,
  Tooltip,
  YAxis,
  Label
} from 'recharts'



export default function Home() {
  
   // Create state variables
   let [responseData, setResponseData] = React.useState('');
   let [ticker, setTicker] = React.useState('');
   let [message, setMessage] = React.useState('');

   // fetches stock data based on parameters
   const fetchData = (e) => {
       e.preventDefault()
       setMessage('Loading...')
       api.stockTimeSeries(ticker)
       .then((response)=>{
          setResponseData(response.data)
          setMessage('')
          console.log(response)
       })
       .catch((error) => {
          setMessage('Error')
          console.log(error)
       })
   }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org"> BitFi </a>
        </h1>
      </main>

      <div
            style={{
                background: 'white',
                padding: '5%',
                fontFamily: "Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,Bitstream Vera Sans Mono, Courier New, monospace "
            }}>
            <h1 className={styles.title}> Search for your favorite Comany</h1>
            <h2>Analyze Stock Data</h2>
            <form onSubmit={fetchData}>
                <fieldset>
                    <legend>Search Stock Market</legend>
                    <label htmlFor="ticker">Enter stock ticker
                        <input
                            required
                            name="ticker"
                            id="ticker"
                            type='text'
                            placeholder='SPY'
                            value={ticker}
                            onChange={(e) => setTicker(e.target.value)}
                        />
                    </label>
                    <button type='submit'>Submit</button>
                </fieldset>
            </form>
            <p>{message}</p>
            <h3>Symbol: {responseData ? responseData.symbol : ''}</h3>
            <p>Daily Time Series with Splits and Dividend Events</p>
            <small>Last Refresh: {responseData ? responseData.refreshed : ''}</small>
            <LineChart
                width={900}
                height={500}
                data={responseData.closePrices}
                margin={{ top: 50, right: 20, left: 10, bottom: 5 }}
                >
                <YAxis tickCount={10} type="number" width={80}>
                    <Label value="Close Price" position="insideLeft" angle={270} />
                </YAxis>
                <Tooltip />
                <XAxis padding={{left: 5, right: 5}} tickCount={10} angle={-60} height={90} dataKey="date" />
                <CartesianGrid stroke="#fafafa" />
                <Line type="monotone" dataKey="close" stroke="#ff7300" yAxisId={0} />
            </LineChart>
        </div>
    </div>

  )
}

//export default async function getStaticProps(){
  //const options = {
    //headers: {
      //'X-Rapid-Api' : '',
      //'X-Rapid-Key' : ''
    //}
  //}
  
  //const res = await fetch ("")
  //const MarketData = await res.json();

  //return {
    //props: {
    //  MarketData
    //}
  //}

//}